#define nx 512
#define ny 512
#define nz 512
#define nv 3
#define prefix "data."
#define suffix ".dbl"
#define datdir "/mnt/lustre/ug4/ugrajs/fiducial_runs/512/"
#define outprefix "vort."
#define f1 20
#define f2 30
#define verbose 0
#define fn  8
#define typed "c"
#define order 2
